description: >-
  Training using $CONFIG on $DATASET
tasks:
  - spec:
      image: $BLUEPRINT
      resultPath: /stage/allennlp/_experiments/
      args:
        - bash
        - scripts/experiments/qa/run_experiment_openbookqa_gpu.sh
        - $CONFIG
      env:
        DATASET: $DATASET
        CONFIG: $CONFIG
        NUMSPLITS: $NUMSPLITS
      datasetMounts:
        - datasetId: $DATASET
          containerPath: /input
        - datasetId: ds_gnguunokqdaf
          containerPath: /glove
        - datasetId: ds_tknztx7lwx9v
          containerPath: /elmo
      requirements:
        gpuCount: 1
